version: '3'

services:

  esp32:
    build: .
    image: daoit/daoit-esp32-mqtt-tls
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    stdin_open: true
    tty: true
    volumes:
      - .:/project
    command: idf.py flash --port /dev/ttyUSB0
  