# version: "3.8"
   
services:


      
  ganache:
      image: trufflesuite/ganache:latest
      container_name: ganache
      ports:
        - "7545:7545" # Exponer el puerto 7545 (Ganache CLI)
      command:
        - --host=0.0.0.0 # Permitir conexiones desde cualquier host
        - --port=7545    # Puerto del servicio Ganache
        - --chain.chainId=1337 # Chain ID personalizado para evitar conflictos con Metamask
        - --wallet.totalAccounts=10 # Número de cuentas preconfiguradas
        - --wallet.mnemonic="candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
    


  smart-contracts-deployer:
    build:
      context: .
      dockerfile: smart-contracts.Dockerfile
    image: poc-ethereum-smart-contracts-deployer
    container_name: poc-ethereum-smart-contracts-deployer
    depends_on:
      - ganache
    volumes:
      - ./abi:/app/build/contracts
      - ~/.aws:/root/.aws
    env_file:
      - ./_ganache.env
    environment:
      - AWS_PROFILE=dev 
    command: /bin/bash -c "truffle migrate --network ganache || true; sleep infinity"
    stdin_open: true
    tty: true

  # smart-contracts-deployer:
  #   build:
  #     context: ./smart-contracts
  #     dockerfile: Dockerfile
  #   image: poc-ethereum-smart-contracts-deployer
  #   container_name: poc-ethereum-smart-contracts-deployer
  #   depends_on:
  #     - ganache
  #   volumes:
  #     - ./abi:/app/build/contracts
  #     - ~/.aws:/root/.aws
  #   env_file:
  #     - ./_ganache.env
  #   environment:
  #     - AWS_PROFILE=dev 
  #   command: /bin/bash -c "truffle migrate --network ganache || true; sleep infinity"
  #   stdin_open: true
  #   tty: true
  





  dapp:
    build:
      context: .
      dockerfile: dapp.Dockerfile
    image: poc-ethereum-dapp
    container_name: poc-ethereum-dapp
    depends_on:
      - ganache
    volumes:
      - ./dapp/index.js:/app/index.js
      - ./abi:/app/abi
      - ~/.aws:/root/.aws
    env_file:
      - ./_ganache.env
    environment:
      - AWS_PROFILE=dev 
    ports:
        - "3000:3000"
  # dapp:
  #   build:
  #     context: ./dapp
  #     dockerfile: Dockerfile
  #   image: poc-ethereum-dapp
  #   container_name: poc-ethereum-dapp
  #   depends_on:
  #     - ganache
  #   volumes:
  #     - ./dapp/index.js:/app/index.js
  #     - ./abi:/app/abi
  #   env_file:
  #     - ./_ganache.env
  #   ports:
  #       - "3000:3000"