# version: "3.8"
   
services:


  poc-ethereum-truffle:
    build:
      context: .
      dockerfile: Dockerfile
    image: poc-ethereum-truffle
    container_name: poc-ethereum-truffle
    # network_mode: host
    stdin_open: true
    tty: true
  
      
  ganache:
      image: trufflesuite/ganache:latest
      container_name: ganache
      ports:
        - "7545:7545" # Exponer el puerto 7545 (Ganache CLI)
      command:
        - --host=0.0.0.0 # Permitir conexiones desde cualquier host
        - --port=7545    # Puerto del servicio Ganache
        - --chain.chainId=1337 # Chain ID personalizado para evitar conflictos con Metamask
        - --wallet.totalAccounts=10 # Número de cuentas preconfiguradas

  dapp:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - ganache
    volumes:
      - ./backend/index.js:/app/index.js
    # working_dir: /usr/src/app
    environment:
      - BLOCKCHAIN_URL=http://ganache:7545
      - CONTRACT_ADDRESS=0xYourSmartContractAddress
    ports:
        - "3000:3000"
    stdin_open: true
    tty: true