# version: "3.8"
   
services:


      
  smart-contracts-deployer:
    build:
      context: ./smart-contracts
      dockerfile: Dockerfile
    image: poc-ethereum-smart-contracts-deployer
    container_name: poc-ethereum-smart-contracts-deployer
    depends_on:
      - ganache
    volumes:
      - ./abi:/app/build/contracts
    command: truffle migrate --network development & 
    stdin_open: true
    tty: true
  





  dapp:
    build:
      context: ./dapp
      dockerfile: Dockerfile
    image: poc-ethereum-dapp
    container_name: poc-ethereum-dapp
    depends_on:
      - ganache
    volumes:
      - ./dapp/index.js:/app/index.js
      - ./abi:/app/abi
    environment:
      - BLOCKCHAIN_URL=http://ganache:7545
    ports:
        - "3000:3000"