# version: "3.8"
   
services:


      
  smart-contracts-deployer:
    build:
      context: ./smart-contracts
      dockerfile: Dockerfile
    image: poc-ethereum-smart-contracts-deployer
    container_name: poc-ethereum-smart-contracts-deployer
    volumes:
      - ./abi:/app/build/contracts
    env_file:
      - ./_sepolia.env
    command: truffle migrate --network sepolia & 
    stdin_open: true
    tty: true
  





  dapp:
    build:
      context: ./dapp
      dockerfile: Dockerfile
    image: poc-ethereum-dapp
    container_name: poc-ethereum-dapp
    volumes:
      - ./dapp/index.js:/app/index.js
      - ./abi:/app/abi
    env_file:
      - ./_sepolia.env
    ports:
        - "3000:3000"