version: '3'

services:

  terraform:
    build: 
      context: .
    image: terraform-deployer
    env_file:
      - dev.env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    volumes:
      - ./terraform:/workspace
    working_dir: /workspace
    # command: ["terraform", "apply", "-auto-approve"]
  