services:
  ca.org1.example.com:
    image: hyperledger/fabric-ca:2.5
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config:/etc/hyperledger/fabric-ca-server

  orderer.example.com:
    image: hyperledger/fabric-orderer:2.5
    environment:
      - FABRIC_LOGGING_SPEC=INFO
    ports:
      - "7050:7050"
    working_dir: /etc/hyperledger/configtx
    command: orderer
    volumes:
      - ./config:/etc/hyperledger/configtx

  peer0.org1.example.com:
    image: hyperledger/fabric-peer:2.5
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    ports:
      - "7051:7051"
    command: peer node start
    volumes:
      - ./crypto-config:/etc/hyperledger/fabric/msp
      - ./config:/etc/hyperledger/fabric/config

