version: "3.8"
   
services:


  poc-ethereum-ganache:
      build:
        context: ./ganache
        dockerfile: Dockerfile
      image: poc-ethereum-ganache
      container_name: poc-ethereum-ganache
      ports:
        - 8545:8545

  poc-ethereum-truffle:
    build:
      context: ./truffle
      dockerfile: Dockerfile
    image: poc-ethereum-truffle
    container_name: poc-ethereum-truffle
    depends_on: 
      - poc-ethereum-ganache
    # network_mode: host
    # ports:
    #   - 8070:8080
    # command:  ["java" , "-jar" , "target/gtrader2-orders-router-launcher-1.0-SNAPSHOT.jar"
    #     , "--serverPort=8080" ,  "--jpaDdlAuto=create"] 
    
    
