FROM hashicorp/terraform:latest

WORKDIR /workspace

COPY terraform/* /workspace/

# COPY entrypoint-create.sh /entrypoint-create.sh

# RUN chmod +x /entrypoint.sh

# ENTRYPOINT ["/entrypoint.sh"]

# entrypoint ["terraform", "apply"]
# CMD ["terraform", "-version"]