version: '3'

services:

  terraform:
    build: 
      context: .
    image: terraform-deployer
    env_file:
      - dev.env
    volumes:
      - ./terraform:/workspace
    working_dir: /workspace
    command: >
      sh -c "
        rm -f terraform.lock.hcl &&
        terraform init &&
        terraform plan &&
        terraform apply -auto-approve &&
        rm -rf .terraform .terraform.lock.hcl
      "
  