# version: "3.8"
   
services:
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: aws-app-runner
    container_name: poc-aws-app-runner
    volumes:
      - ./index.js:/app/index.js
    ports:
        - "3000:3000"