Profiles:
  OrdererGenesis:
    Orderer:
      OrdererType: solo
      Addresses:
        - orderer.example.com:7050
      BatchTimeout: 2s
      BatchSize:
        MaxMessageCount: 100
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
    Consortiums:
      SampleConsortium:
        Organizations:
          - Name: Org1
            MSPDir: /etc/hyperledger/fabric/msp/org1
            Policies:
              Readers:
                Type: ImplicitMeta
                Rule: "ANY Readers"
              Writers:
                Type: ImplicitMeta
                Rule: "ANY Writers"
              Admins:
                Type: ImplicitMeta
                Rule: "MAJORITY Admins"
    Application:
      ACLs: {}
      Policies:
        Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
        Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
        Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
