# version: "3.8"
   
services:



  truffle-deployer:
    build:
      context: .
      dockerfile: Dockerfile.truffle-deployer
    image: truffle-deployer
    container_name: truffle-deployer
    volumes:
      - ~/.aws:/root/.aws
    env_file:
      - ./_sepolia.env
    environment:
      - AWS_PROFILE=dev 
    command: truffle migrate --network sepolia & 
    stdin_open: true
    tty: true
  
  dapp:
    build:
      context: .
      dockerfile: Dockerfile.dapp
    image: dapp
    container_name: dapp
    volumes:
      - ~/.aws:/root/.aws
    env_file:
      - ./_sepolia.env
    environment:
      - AWS_PROFILE=dev 
    ports:
        - "3000:3000"

