version: '3'

services:

  app:
    build: .
    image: ceiot/poc-esp32-mqtt
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    volumes:
      - .:/project
    command: idf.py clean build flash --port /dev/ttyUSB0
  